In [1]:
import numpy as np
a=np.zeros((4))
print(a)

[0. 0. 0. 0.]


In [2]:
a=np.array([1,2,3,4])
b=np.array([[1,2],[3.5, 4.2]])
print("a={0}".format(a))
print("b={0}".format(b))

a=[1 2 3 4]
b=[[1.  2. ]
 [3.5 4.2]]


In [3]:
a=np.zeros((3))
b=np.ones((2,3), dtype=int)
print("a={0}".format(a))
print("b={0}".format(b))

a=[0. 0. 0.]
b=[[1 1 1]
 [1 1 1]]


In [4]:
a=np.linspace(1,10,6)
print("a={0}".format(a))

a=[ 1.   2.8  4.6  6.4  8.2 10. ]


In [5]:
a=np.arange(1,10,1)
print("a={0}".format(a))

a=[1 2 3 4 5 6 7 8 9]


In [6]:
a=np.array([[1,2],[3,4]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

2
(2, 2)
4
int64


In [7]:
a=np.array([2.45, 3.75])
a[0]=16
b=np.array([[0,1],[2,3]])
print(a[0])
print(b[1,1])

16.0
3


In [8]:
a=np.array([1,2,3,4])
b=np.array([2,4,8,16])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**2)
print(np.sqrt(b))

[ 3  6 11 20]
[ -1  -2  -5 -12]
[ 2  8 24 64]
[0.5   0.5   0.375 0.25 ]
[ 1  4  9 16]
[1.41421356 2.         2.82842712 4.        ]


In [9]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,4],[8,16]])
print(a@b)

[[18 36]
 [38 76]]


In [10]:
a=np.linspace(0,10,11)
print(a)
print(a[2:5])
print(a[1:8:2])

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[2. 3. 4.]
[1. 3. 5. 7.]


In [11]:
mat=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(mat[:,2])
print(mat[3,:])
print(mat[:,2:4])

[ 3  7 11 15]
[13 14 15 16]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]


In [12]:
a=np.array([1,1])
b=np.array([2,2])
c=np.array([3,3])
print(np.hstack((a,b,c)))
print(np.vstack((a,b,c)))

[1 1 2 2 3 3]
[[1 1]
 [2 2]
 [3 3]]


In [13]:
a=np.array([1,2,3])
print(a)
a=np.append(a,4)
print(a)
a=np.insert(a,2,7)
print(a)

[1 2 3]
[1 2 3 4]
[1 2 7 3 4]


In [14]:
a=np.array([[1,2],[3,4]])
print(a)
a=np.append(a,[[5],[6]],axis=1)
print(a)

[[1 2]
 [3 4]]
[[1 2 5]
 [3 4 6]]
